sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: q5T4oWI6naH2R1lfzaDu9mpZHR3n1OTcwLBb+KOYAGr0JwiLjQHSEAORP8jHuZt7I/OZ1L0SXLVoanRPOU1EHxn/4UNo8uNu9csN9Ekj2d4VHGzuygZZ2be/zjZZ5i9hzF4u0a6vl0LVMC5TTlRTmyyngafR52PPo0ynkagfOP4LrkG/aybRA9MNzmsYYgtovPe36EVZJUQFya+UOtbfU+ooyEuv9pJ5nYTGFa023Uwe962pZJGNYi0gDP5hfA7BITUMnaGqSfAF8YdYm5abbKZX94ehRM8ffOM8iwQ2avmiSnt88T8uZeipt9bvAcn0GLXyy3c9UKIexuIw1TRPI7nNTFjv2eyeR9nYMdybXQZmtK3/Ru2pPhb93rQW9+WVaX0AriM4LrVtS0VxMERO9XrBCvFUMkyFVIL7jhBhORZ8NNl/rOSsYWKCGR+N1rkN74kGVlldxBohNOMizvKupX7tLL201lx4lzz2z8FubtSIVRi17+FqiFEH0/+Z/3hWtni6JtXAEMGxo+447q3cI3x5zXKzhhMD5nSxxHILcppYWAQAFLVFuUv9Qgrz+biMiJ9EMnZ2qYotab/Fo20KngL8BJ+TANgQstpuXuEnaf9wj/hNJodMdUkow4VriWhZCw3tqW5qbLrmc4XjhoJ4cJPC24rq1o6LJBI5iZngeqA=
    - secure: dRhYVk6tgdNGjy1ZjBqiJzT5QUwrn03AwX9y/aLtRWlFZkzFvyROCfJtH089D4XEb/0pjKQ1ARpdwZeW50Kk+XZfif5TeKlbR+o1yqNHKUSxLHeHhyyxCLTRWaQSDBMxli88eb8WhYq82CKWEBgqgQq4zpu4pyuQGqX6QarApZ+MHoftQ18ZzCcTGOeCa0ZwGVvcnKU+qRVY35VbQ+PvtBN++xfVWntfoZqFHY1R9fy1Lir7I3pMJemLgJiYmrz3VXb2yGfqoAV4CdJW4T9jDhmh/puDME2x04n1QVitBNj+mXnDzZU6aP9GQ9VAekOyncbqhhNfC7dmDIL9OpccrKh+/0i1FpCYfMrDRYdMfFelkIHkJHHkJzB/CuGA5cQIAC8RUvUyc9kUPAG4tMYi1ficLM88YAfANLDfOxbx5AbZqUTlUgc8lqdpbLh4y6BEkuq3fGs1NcH71gH6PylsUqjDv8JD56dsdnChk0Ner34uCVe3cVYit3xMCthTEcaIO8HDCQOCXCJeoqjKh02KgFNyBVtAuOgdNKHxunmukJ6d0VIenzmOs6kDoFjM9SLBSNiRDPZ3xuoyVgZ/HNs4qG5SkMC3PMct81vV2nNT4c39lkJuoWlLzzfQa7+1GaKB2d/s7tBbLRLzbOp4NfGQ7oAOLJgtpBZzn79Tr4teUa8=
